//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod note;
pub mod note_alias;
pub mod note_link;
pub mod note_link_index_state;
pub mod project;
pub mod workspace_link;
pub mod workspace_link_index_state;
pub mod workspace_reference_alias;
