//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "note")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub title: String,
    pub project_id: Option<i64>,
    pub file_path: Option<String>,
    pub file_managed_by_app: bool,
    pub cached_content: String,
    pub file_missing_since: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
    pub is_pinned: bool,
    pub last_opened_at: Option<i64>,
    pub deleted_at: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub project: HasOne<super::project::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
