//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::note::Entity as Note;
pub use super::note_alias::Entity as NoteAlias;
pub use super::note_link::Entity as NoteLink;
pub use super::note_link_index_state::Entity as NoteLinkIndexState;
pub use super::project::Entity as Project;
pub use super::workspace_link::Entity as WorkspaceLink;
pub use super::workspace_link_index_state::Entity as WorkspaceLinkIndexState;
pub use super::workspace_reference_alias::Entity as WorkspaceReferenceAlias;
