[package]
name = "workspace"
version.workspace = true
publish = false
edition.workspace = true

[features]
default = []
test-support = []

[dependencies]
gpui-kit.workspace = true
anyhow.workspace = true
lsp-types.workspace = true
storage = { path = "../storage" }
runtime = { path = "../runtime" }
settings = { path = "../settings" }
serde.workspace = true

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
